spring:
  application:
    name: jwt-token
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_tokens?createDatabaseIfNotExist=true
    username: root
    password: 123456
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolJwt
  jpa:
    hibernate:
      ddl-auto: update


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1h in millisecond